### ISSUE TITLE
able to hset of sub-lane speed to "auto"; should not allow

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#19]
Normally we don't allow sub-lane of an interface to be set separately.  Redis seem to allow this when sub-lane speed is set to "auto".  Doesn't seem to do anything adversely to the port, but behavior is incorrect.

fyang@invader17:$ goes hget platina vnet.eth-32-1.speed
100g
fyang@invader17:$ goes hset platina vnet.eth-32-2.speed 100g
hset: ERROR invalid speed
fyang@invader17:$ goes hset platina vnet.eth-32-2.speed auto
1
fyang@invader17:$ goes hset platina vnet.eth-32-3.speed auto
1
fyang@invader17:$ goes hset platina vnet.eth-32-4.speed auto
1
fyang@invader17:$ goes hget platina vnet.eth-32-2.speed
auto

**Comment by fszyang** [comment]
Still there in latest.  Some combination will cause redsid to hang.
fyang@invader2:$ sudo goes hget platina package | grep version:
    version: 12bd0121f22fb1d63ccc9879cc7fe11464655f7c
    version: 1af481b2eff2a5368950b58aac47b5e313ea7663
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18
fyang@invader2:$ goes hset platina vnet.eth-9-1.speed 100g
1
fyang@invader2:$ goes hget platina vnet.eth-9 | grep speed
vnet.eth-9-1.speed: 100g
fyang@invader2:$ goes hset platina vnet.eth-9-2.speed auto
1
fyang@invader2:$ goes hget platina vnet.eth-9 | grep speed
vnet.eth-9-1.speed: 100g
vnet.eth-9-2.speed: auto
fyang@invader2:$ goes hget platina vnet.eth-9 | grep link
vnet.eth-9-1.link: false
fyang@invader2:$ goes hset platina vnet.eth-9-1.speed auto
1
fyang@invader2:$ goes hget platina vnet.eth-9 | grep link
vnet.eth-9-1.link: true
fyang@invader2:$ goes hset platina vnet.eth-9-2.speed 100g

hset: read unix @->/run/goes/socks/redisd: i/o timeout
fyang@invader2:$ sudo goes status
GOES status
======================
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - Not OK
status: read unix @->/run/goes/socks/redisd: i/o timeout

**Comment by fszyang** [comment]
Fixed with commit (in fe1) 770ae3950eb02aa8a370732fb21e71b2e1fa4566

**Comment by jignesh045** [comment]
With the recent build (shown below as 11 March), i have found that it is still reproducing.

```
root@invader29:/home/fyang# ls -la | grep goes
-rwxr-xr-x  1 fyang fyang 30919384 Mar 11 18:10 goes-platina-mk1
root@invader29:/home/fyang#

root@invader30:~# goes hget platina package | grep version:
    version: 30f396d35e419a5cc0006e9305a91ca31ce8cdd5
    version: 716f29ca72f20ac3288bbd2857eb55cfcadb63eb
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18
root@invader30:~#
```

Below is the executed commands
```
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1-1.speed
25g
root@invader30:/home/jignesh#
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1-2.speed
25g
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1-3.speed
25g
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1-4.speed
25g
root@invader30:/home/jignesh#
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-2.speed 100g
hset: ERROR invalid speed
root@invader30:/home/jignesh#
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-2.speed auto
1
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-3.speed auto
1
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-4.speed auto
1
root@invader30:/home/jignesh#
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1-2.speed
autoneg
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-4.speed 100g
hset: ERROR invalid speed
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes status
GOES status
======================
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK
root@invader30:/home/jignesh#

root@invader30:/home/jignesh# goes hget platina vnet.eth-1 | grep speed
vnet.eth-1-1.speed: 25g
vnet.eth-1-2.speed: autoneg
vnet.eth-1-3.speed: autoneg
vnet.eth-1-4.speed: autoneg
vnet.eth-10-1.speed: 100g
vnet.eth-11-1.speed: 100g
vnet.eth-12-1.speed: 100g
vnet.eth-13-1.speed: 100g
vnet.eth-14-1.speed: 100g
vnet.eth-15-1.speed: 100g
vnet.eth-16-1.speed: 100g
vnet.eth-17-1.speed: 100g
vnet.eth-18-1.speed: 100g
vnet.eth-19-1.speed: 100g
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-2.speed auto
1
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1- | grep speed
vnet.eth-1-1.speed: 25g
vnet.eth-1-2.speed: autoneg
vnet.eth-1-3.speed: autoneg
vnet.eth-1-4.speed: autoneg
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1- | grep link
vnet.eth-1-1.link: false
vnet.eth-1-2.link: false
vnet.eth-1-3.link: false
vnet.eth-1-4.link: false
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-1.speed auto
1
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hget platina vnet.eth-1- | grep link
vnet.eth-1-1.link: false
vnet.eth-1-2.link: false
vnet.eth-1-3.link: false
vnet.eth-1-4.link: false
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes hset platina vnet.eth-1-2.speed 100g
hset: ERROR invalid speed
root@invader30:/home/jignesh#
root@invader30:/home/jignesh#
root@invader30:/home/jignesh# goes status
GOES status
======================
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK
root@invader30:/home/jignesh#
```
